## Sample Data

In [2]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[0.5, 4.5, -1.2],
                       [2.1, -1.2, 0.2],
                       [1.1, -8.9, 4.8],
                       [-4.3, 1.7, 6.2]])

sample_data

array([[ 0.5,  4.5, -1.2],
       [ 2.1, -1.2,  0.2],
       [ 1.1, -8.9,  4.8],
       [-4.3,  1.7,  6.2]])

In [3]:
sample_data.shape

(4, 3)

## Binarisation

In [4]:
sample_data

array([[ 0.5,  4.5, -1.2],
       [ 2.1, -1.2,  0.2],
       [ 1.1, -8.9,  4.8],
       [-4.3,  1.7,  6.2]])

In [7]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 1.],
       [0., 1., 1.]])

## Scaling

In [9]:
sample_data

array([[ 0.5,  4.5, -1.2],
       [ 2.1, -1.2,  0.2],
       [ 1.1, -8.9,  4.8],
       [-4.3,  1.7,  6.2]])

In [10]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.75      , 1.        , 0.        ],
       [1.        , 0.57462687, 0.18918919],
       [0.84375   , 0.        , 0.81081081],
       [0.        , 0.79104478, 1.        ]])

In [11]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.75      , 1.        , 0.        ],
       [1.        , 0.57462687, 0.18918919],
       [0.84375   , 0.        , 0.81081081],
       [0.        , 0.79104478, 1.        ]])

## L1 Normaliztion: Least Absolute Deviations

In [12]:
sample_data

array([[ 0.5,  4.5, -1.2],
       [ 2.1, -1.2,  0.2],
       [ 1.1, -8.9,  4.8],
       [-4.3,  1.7,  6.2]])

In [13]:
L1_normalization_data = preprocessing.normalize(sample_data, norm='l1')
L1_normalization_data

array([[ 0.08064516,  0.72580645, -0.19354839],
       [ 0.6       , -0.34285714,  0.05714286],
       [ 0.07432432, -0.60135135,  0.32432432],
       [-0.35245902,  0.13934426,  0.50819672]])

## L2 Normaliztion: Least Squares

In [14]:
sample_data

array([[ 0.5,  4.5, -1.2],
       [ 2.1, -1.2,  0.2],
       [ 1.1, -8.9,  4.8],
       [-4.3,  1.7,  6.2]])

In [16]:
L2_normalization_data = preprocessing.normalize(sample_data, norm='l2')
L2_normalization_data

array([[ 0.10674602,  0.96071418, -0.25619045],
       [ 0.86528993, -0.49445139,  0.08240856],
       [ 0.108145  , -0.87499137,  0.47190546],
       [-0.55596218,  0.219799  ,  0.80161989]])